### ISSUE TITLE
Plug-in "org.springframework.tooling.boot.ls" was unable to instantiate class "org.springframework.tooling.boot.ls.DelegatingStreamConnectionProvider".

### ISSUE THREAD

**Issue by hongli8881** [spring-projects/sts4#145]
org.eclipse.core.runtime.CoreException: Plug-in "org.springframework.tooling.boot.ls" was unable to instantiate class "org.springframework.tooling.boot.ls.DelegatingStreamConnectionProvider".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:200)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:934)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:114)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:196)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:532)
	at org.eclipse.lsp4e.LanguageServerWrapper.getServerCapabilities(LanguageServerWrapper.java:563)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrappers(LanguageServiceAccessor.java:301)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfosFor(LanguageServiceAccessor.java:444)
	at org.eclipse.lsp4e.operations.color.DocumentColorProvider.lambda$0(DocumentColorProvider.java:53)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NoClassDefFoundError: org/springframework/tooling/boot/ls/SpringBootLanguageServer
	at org.springframework.tooling.boot.ls.DelegatingStreamConnectionProvider.<init>(DelegatingStreamConnectionProvider.java:62)
	at sun.reflect.GeneratedConstructorAccessor118.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:190)
	... 16 more

**Comment by martinlippert** [comment]
I am a bit puzzled by this error message. We have seen this a number of times now, so there must be a real underlying issue somewhere, but I have no idea what is causing this.

Does this happen every time you start STS4 and start using it? If so, can you help us a bit? Open the Console view and switch it to the OSGi Host Console. Then type `ss` for `short status` and press enter. I would like to learn about the status of the bundle `org.springframework.tooling.boot.ls`. What does it say?

Btw, you could also try to workaround this issue by starting STS from the command line with the `-clean`option, maybe just to see if that makes a difference.

**Comment by kdvolder** [comment]
We'll close this ticket. Still worried there's a problem here somewhere that we don't yet understand. But until we get another chance to trouble-shoot there isn't much more we can do right now. And sounds like the problem has, at least for now, been solved by restarting.

**Comment by vdillon** [comment]
I'm seeing this issue constantly.  Every time I open a java file the log fills up with the message.  I've tried the following to no effect:

- set the -vm in SpringToolSuite4.ini to a JDK
- starting with -clean
- removing lombok support

**Configuration**
- Windows 10 Pro version 1809
- jdk1.8.0_192_x64
- spring-tool-suite-4-4.0.1.RELEASE-e4.9.0-win32.win32.x86_64
- lombok 

**SpringToolSuite4.ini**
```
-startup
plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.800.v20180827-1352
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vm
H:\Edge2Web\jdk1.8.0_192_x64\bin\javaw.exe
-vmargs
-Dosgi.requiredJavaVersion=1.8
--add-modules=ALL-SYSTEM
-Xms40m
-Xmx1200m
-javaagent:H:\Edge2Web\sts-4.0.1.RELEASE\lombok.jar

```
Not sure if this is relevant.  The machine has two intenet adapters.

**Comment by kdvolder** [comment]
Several people have reported having this issue but we can't reproduce it. However, we did add some additional logging / info dumping to the latest STS 4 release (version 4.0.2) that *might* give us some more information.

If you are using 4.0.2, can you please get the Eclipse error log and attach it here. You can export it to a file from the 'Error log' view which you can open via "Windows >> Show View >> Other >> Error Log". 

If you are not yet using 4.0.2, consider switching, and if the problem happens again, please attach the log. Thanks.

> Not sure if this is relevant. The machine has two intenet adapters.

Probably not relevant. But anything is possible. Still we think its more something to do with Eclipse p2 classloaders and bundles which should not be affected at all by your network setup.

**Comment by vdillon** [comment]
@kdvolder thanks for the quick response.  I have tried 4.0.2.  Here's the log.

[sts-4.0.2.log](https://github.com/spring-projects/sts4/files/2659884/sts-4.0.2.log)

I'm not seeing the same errors in the log (from the title).  Instread, there are many UnsupportedOperationException errors with no message.

I still can't get Content Assist, Code Completion, and Information Hover to work.

Another thing I noticed with 4.0.2 vs 4.0.1.  When I open a Spring Boot App Debug Configuration, the Override properties panel now displays as a Spring Properties editor.  Here's a screen capture:

![springbootappdebugconfiguration](https://user-images.githubusercontent.com/663384/49688483-ecf68f80-fae0-11e8-990a-3488ea1980b5.jpg)

**Comment by martinlippert** [comment]
@vdillon the embedded properties editor in the launch config is by design, we replaced the previous table-based UI with a full-blown properties editor that offers content-assist, help, etc. So that is a feature, not a bug... :-)

But taking your report above into account it sounds like the content-assist etc. is not working, so maybe it is also broken in the embedded editor. Is that correct? Or does it work in that launch config embedded editor?

The log that you attached doesn't contain anything that hints at the underlying issue. Can you open the `Error Log` view to see if there is anything related showing up?

I also noted that you have the Lombok agent installed in your `SpringTools4.ini` file. I vaguely remember that we had several people running into this issue also having the Lombok agent installed. I have no clue if this is indeed related or not, so can you try and remove the Lombok agent from the ini file for testing purposes? Would be quite interesting to see if that improves the situation.

**Comment by martinlippert** [comment]
@vdillon Sounds good and thanks for letting us know. If you come across any further issues, please do not hesitate to contact us and comment here or, even better, file a new issue. Thanks again!

**Comment by madhawik** [comment]
I was getting same exception with sts-4.8.0.RELEASE version. I tried multiple solutions available on internet but nothing has worked for me. 

Then I decided to again extract the tool installation jar file. Earlier I unpacked spring-tool-suite-4-4.8.0.RELEASE-e4.17.0-win32.win32.x86_64.self-extracting.jar file manually. This time I run the command **`java -jar spring-tool-suite-4-4.8.0.RELEASE-e4.17.0-win32.win32.x86_64.self-extracting.jar`** .  

Finally this resolved my problem.
