### ISSUE TITLE
Latest STS4 doesn't show RequestMapping in multi module projects

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#469]
Latest STS4 doesn't show RequestMapping in multi module projects. I have a spring mvc project which has few controllers in a maven sub module. The controllers are in generated source code folder. These RequestMapping are not considered in the symbols list. But other spring configurations from this module are taken in.  In Eclipse time to time these symbols shows up, but these symbols are not showing up in my IntelliJ Idea integration with the language server.

Currently i'm using 1.15.0-SNAPSHOT language server version in the IJ integration. The REST symbols are shown correctly for simple spring demo apps in both IDEs without any issues.

**Comment by BoykoAlex** [comment]
I have tried the latest STS4 (4.6.2) with multi module project:
- https://github.com/spring-io/initializr (Backend service)
- https://github.com/spring-io/start.spring.io (Frontend service)

There are request mapping in `initializr-web` (backend) and `start-site`(frontend) and they all show up in workspace symbols.
Any chance you can try the latest STS4 or attach you project perhaps?

**Comment by gayanper** [comment]
Is there are a default sts4 LS log file when starting from command line default parameters  @BoykoAlex ? Unfortunately I cannot share the project code, But I observed this might be happening due to some of my configuration file, Because when I remove some spring config files, there REST endpoint appears in the symbols. Works fine in Eclipse, only in my IJ integration this happens, Now i'm running against the latest LS snapshot as well.

**Comment by gayanper** [comment]
Further investigations shows that the following kind of Bean configuration is causing the failure
```
  @Bean
  public XXXMapperFactory getXXXMapperFactory(List<XXXMapper> mappers)
  {
    return new XXXMapperFactory (mappers);
  }
```

removing this particular bean definition from the configurating file cause the request mapping symbols to be back in list.

even adding it back cause the mapping symbols to be still there. Seems like the LS issue to me.

**Comment by gayanper** [comment]
I also tried to enable logs, but that cause a LS issue some the capabilities are not sent to my LS Client rather they are logged into log file. I think ideally this class should pass through logs https://github.com/spring-projects/sts4/blob/b9c491466f121f483a2a095ccea8e6b19d36b0af/headless-services/commons/commons-util/src/main/java/org/springframework/ide/vscode/commons/util/LogRedirect.java when the language server is used with ProcessStreamConnectionProvider

**Comment by gayanper** [comment]
@BoykoAlex i did some more investigation and found out that the rest mappings are available in the sts4 symbols cache file. It doesn’t returned from get symbols end point. But if i do a change on the file I mentioned in my previous comment, after that i will see all the rest mappings

**Comment by martinlippert** [comment]
@gayanper I think I lost the overview here a bit. Hope you can help me with that.

- What happens if you shutdown everything, then delete the cached symbol data, and restart everything? Do the request mappings show up then?
- And it happens only with your IntelliJ integration and works fine in Eclipse/STS4?

And is this "doesn't work" really related to the bean method that you mentioned above or could that be related to changing the file instead? (independent of the exact content)

**Comment by gayanper** [comment]
@martinlippert 
- Even if i shutdown and clear the cache and start up the problem is still there.
- Works fine with eclipse, but the problem is there in vscode as well.

Not the bean method seems to have nothing to do with, but i found out that its the problem with the file, if i do a change in file like commenting out a bean and reverting it, then suddenly the REST symbols are back until a full index happens again.

I found another similar multi project which has the same issue, in that i cannot get REST symbols in vscode as well. And in this project i cannot get the REST symbols at all even if i change some files. But in the symbol cache json file i see the REST symbols. May be vscode is not detecting since the REST symbols are in generated source code folders.

One thing i noted is, in IJ integration it generates a huge symbol file, but in vscode there is a symbol file per each sub module.

**Comment by martinlippert** [comment]
Sounds like it might be related to the way the project information is being used to find the java sources for doing the bulk scan. Updating individual files triggers the symbol scan in a slightly different way, so we should probably look in more detail at the project setup and how that ends up being communicated to the language server and ends up in the list of java files to scan for symbols.

Do you think it would be possible to setup a simple sample project that has the same structure (with generated java files)?

**Comment by gayanper** [comment]
@martinlippert one thing to note is that these jsons are huge like more than 5k lines. I tried with simple spring boot projects and every thing is working even in generated source code folders. So its not a issue in IJ integration.

**Comment by gayanper** [comment]
@martinlippert Seems like the bulk scans catches the symbols, because when i search the symbol cache i can see those entries in it. They are not returned as part of the symbols endpoint it seems.

**Comment by gayanper** [comment]
@martinlippert i tried this project which doesn't work in vscode in eclipse as well. It doesn't show up REST symbols. unfortunately we cannot enable logging for language server when integrating in IJ. if i enable logging my LS doesn't because of https://github.com/spring-projects/sts4/issues/469#issuecomment-635518589

**Comment by martinlippert** [comment]
I looked at the code again and the symbol infrastructure returns a max of 50 symbols when asked for all symbols (to avoid pumping a huge amount of data over through the pipe). So I am wondering why the symbols do not show up (since you mentioned they are being created and stored in the cache)... I must admit I am quite puzzled about this...

**Comment by gayanper** [comment]
Well may be something happens with the @/ search pattern, can it be a issue with processing that pattern.

**Comment by gayanper** [comment]
@martinlippert  @BoykoAlex  I manage to reproduce this with sts4 headless project.

[headless-services-aggregator-symbols.zip](https://github.com/spring-projects/sts4/files/4705608/headless-services-aggregator-symbols.zip)

[test-webapp.zip](https://github.com/spring-projects/sts4/files/4705610/test-webapp.zip)
try to extract the test-webapp.zip into headless-services folder.

**Comment by gayanper** [comment]
I found an issue in the IJ LSP Client that it doesn't pass in the search query into symbols request. This result in STS4 server always returning the first 50 results. Now I have fixed it in LSP Client, and the project I attached in  https://github.com/spring-projects/sts4/issues/469#issuecomment-636324780 is fixed by it. I will also try this fix on the other project as well.

**Comment by martinlippert** [comment]
@gayanper great to hear that you found out what is going on here. Let us know if this fixes the problem using the other project as well, so that we could close this issue in case it does.

**Comment by gayanper** [comment]
Works like a charm, The search is much responsive now as well. Thanks @martinlippert for the tip about the maximum 50 results :+1:

**Comment by martinlippert** [comment]
Great to hear that...!!! 😀

**Comment by ab1123** [comment]
I am using Vs code and the same issue persists for me. can anyone please tell me what to do

**Comment by martinlippert** [comment]
@ab1123 Can you provide us with a few more details and/or maybe attach a sample project and a few steps how to reproduce this?
