### ISSUE TITLE
remove WTP-based HTML tooling from Spring Tools 4 distribution

### ISSUE THREAD

**Issue by 4javier** [spring-projects/sts4#572]
_I cross-post this issue from WildWebDeveloper project, because on a vanilla Eclipse installation it doesn't show up.
https://github.com/eclipse/wildwebdeveloper/issues/552
I tried to install latest snapshot as suggested, with no luck. (On plain Eclipse there's no need to update the plugin, it works even with release)._

Every angular directive inside any template gets marked as undefined, but at the same time, its doc gets correctly shown on hover.
![immagine](https://user-images.githubusercontent.com/459381/100524594-b75d7c00-31b9-11eb-8bda-a43af7af8949.png)

To quickly reproduce the issue, just import this basic project and try to validate app.component.html
https://github.com/4javier/angular-ivy-base

**Comment by martinlippert** [comment]
Can you please double check this with the latest STS 4.9.0 release? It also includes the latest Wild Web Developer components. In addition to that please make sure to open the file with the "Generic Text Editor", since this uses the Angular tooling of WWD.

Just opening the file with a double click uses the old HTML editor from WTP, which doesn't know much about Angular, I guess.

With regards to the update path:
Using the latest snapshot update site from WWD should work now, there was most likely a compatibility issue with the previous versions that we used that prevented the update in the past. We certainly don't restrict the included WWD version down to the specific one.

**Comment by 4javier** [comment]
@martinlippert 
I don't know why did you close the issue.
I'm on 4.9.0 and the problem is still present.
I always used Generic Text Editor and I set it up as associated editor for every web related filetype, otherwise it's like not using WWD at all.
The problem is due to the HTML Validator that STS is shipped with, and that's by default enabled to run on "Manual" and "Build" (don't know what "build" could mean talking about html files...)
Disabling it from Window→Preferences→Validation→HTML Syntax Validator solved the issue.
Right way would have been to add Angular elements, directive and attributes to its list, but doing it manually is a pain, and I'm not sure it's feasible for things like directives and bound DOM properties.

**Comment by martinlippert** [comment]
@4javier The solution here would be to finally get rid of the old WTP-based HTML tooling that sneaked into the STS4 distribution. We don't really include this on purpose, it makes its way into the distribution as a dependency to some other feature that we want to include.

So you are right, we should keep it open and see how we can get rid of the remaining old HTML tooling components. Would it be fine with you if we rename this issue accordingly?

**Comment by 4javier** [comment]
Sure.
Feel free to rename it in the more meaningful way.
I think it's even good to put here the link to the generic WTP ticket:
https://github.com/spring-projects/sts4/issues/354
Later, I'll check if there's a way to disable HTML Synatx validator by default, and eventually link it to you.

**Comment by 4javier** [comment]
It seems that this is the value that disable both manual both build html validator
`/instance/org.eclipse.wst.validation/vals/org.eclipse.wst.html.core.HTMLValidator/global=FF01`

**Comment by martinlippert** [comment]
I removed the m2e-wtp features for jaxrs and jsf, which removes more of the additional WTP tooling dependencies. Feel free to download a latest CI distribution build from here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html - and give it a try.

**Comment by 4javier** [comment]
Perfect @martinlippert 
Now HTML Syntax Validator is not listed at all inside Preference→Validation.
Even better than disabling it by default.
Thanks a lot.

**Comment by martinlippert** [comment]
@4javier Great to hear, thanks for letting us know.

**Comment by perry2of5** [comment]
Removing WTP seems to break xsd resolution in Wild Web Developer. See discussion here: https://github.com/eclipse/wildwebdeveloper/issues/778

**Comment by perry2of5** [comment]
WildWebDeveloper recommended filing an issue with lemminx to resolve this. Since the developer is also a lemminx developer, I think this will fix the issue in the long run :)

In the short run, either download the xsd files you need manually and create a catolog or install WTP if you run into this issue.
