### ISSUE TITLE
Outline View is broken again on Windows

### ISSUE THREAD

**Issue by mygithubdevaccount** [spring-projects/sts4#742]
**Describe the bug**
- Symbols are not shown in the Outline view
- Searching for Spring Symbols (Ctrl+Shift+O) is also not working

**To Reproduce**
- Create a simple Spring Boot project with Spring Initializer
- Select a Spring annotated class
- At first symbols show up for a brief moment then they disappear and never come back
- Restarting the language server does not help

**Important**

- This only affects Windows, it's working fine on Ubuntu (haven't tested it on macOS)
- related to closed issue: https://github.com/spring-projects/sts4/issues/627

**Sample**

![test](https://user-images.githubusercontent.com/101020513/156919653-192e3e43-c93c-411d-aaa6-013e6764ca6b.gif)

On Ubuntu symbols show as expected:

![ubuntu](https://user-images.githubusercontent.com/101020513/156919848-ae44d9d4-abab-4b24-8379-5da07deb902c.png)

I'd be happy to provide any log files or further information.

**Additional Info**
OS: Windows 10
VS Code: 1.65.0
Java Extension (Lanugage Support): 1.4.0 (March 3rd, 2022)
Spring Boot Tools: 2022-02-02 (4.13.1 RELEASE, incl. language servers version 1.30.0)
JDK: openjdk 17.0.1 2021-10-19

**Comment by mygithubdevaccount** [comment]
[log.txt](https://github.com/spring-projects/sts4/files/8192398/log.txt)

I have attached the log file. No error messages visible.

**Comment by BoykoAlex** [comment]
Seems like a VSCode bug to me (raised https://github.com/microsoft/vscode/issues/144698). The doc URI from **vscode-languageclient** comes in with escaped drive colon which seems wrong to me:
```
[Trace - 12:35:52 PM] Sending request 'textDocument/documentSymbol - (22)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/sasha/Documents/workspace-spring-tool-suite-4-4.9.0.RELEASE/spring-petclinic/src/main/java/org/springframework/samples/petclinic/owner/PetRepository.java"
    }
}
```

**Comment by BoykoAlex** [comment]
Likely that downgrading VSCode to older version would fix this... I saw the issue in 1.63 too though...

**Comment by BoykoAlex** [comment]
Fixed on Spring Boot LS side: 58f43006d8187d19e0fd55f6b14e36378d111d77

**Comment by mygithubdevaccount** [comment]
It's really wired. Sometimes (I've deleted the symbol cache and restarted VSCode) then after a while the symbols come back. But when I try to edit it the disappear again:

![bug](https://user-images.githubusercontent.com/101020513/157329766-270f75be-a10e-4f58-aa56-5359abeb25d9.gif)

The Symbol cache JSON file has both c%3A and C: entries. But works (when it works) for both of them.

**Comment by mygithubdevaccount** [comment]
> Fixed on Spring Boot LS side: [58f4300](https://github.com/spring-projects/sts4/commit/58f43006d8187d19e0fd55f6b14e36378d111d77)

Can I test this somehow?

**Comment by mygithubdevaccount** [comment]
I have compiled your commit myself. Two observations:

a) This does not solve the bug. Unfortunately the bug is much more complex it seems.
b) The symbolCache file has no c%3A escaped entries anymore, but that was not the cause of the bug unfortunately

**Comment by BoykoAlex** [comment]
Looks like we misunderstood how doc symbols are supposed to work...
We update the doc symbol index after file is saved. However, when file is saved doc symbols view is not refreshed. Doc symbols view (the Outline) is refreshed on document changes, i.e. when user types. Therefore, I suppose if you enter a new endpoint, save the file and then press space or enter key while still in the editor you may see the correct doc symbols. The same issue is present on other platforms.

**Comment by BoykoAlex** [comment]
Should be fixed now with d350da5992d2e3825bc36e07fddce3d978bcc2ab
