### ISSUE TITLE
Unable to install extension 'pivotal.vscode-spring-boot' as it is not compatible with VS Code '1.68.1'.

### ISSUE THREAD

**Issue by TwistyPop** [spring-projects/sts4#967]
**Describe the bug**
Unable to install any version of sts4 using either visual studio code market place or downloading the vsix and installing it manually. I attempted vscode versions from 1.31 all the way to 1.68.1. Seems like something odd is afoot.

**To Reproduce**
download vs code (1.68.1) 
install jdk 17
install spring boot extension pack.

Spring Initializr Java support and Spring Boot Dashboard install fine but Spring Boot Tools fails installation with message "Unable to install extension 'pivotal.vscode-spring-boot' as it is not compatible with VS Code '1.68.1'."

Also attempted to install Spring Boot Tools separately both from vs code market place and as a vsix manual install. It always fails with the same message.

System specs:
Windows 10.0.19044 build 19044

**Comment by BoykoAlex** [comment]
Why don't you upgrade VSCode to the latest (1.74) and try installing it again?

**Comment by TwistyPop** [comment]
@BoykoAlex I work for a enterprise that manages applications and versions through an app manager and "appstore". 1.74 is not approved (yet). The latest version I have available is 1.68. I had 1.31 prior to upgrading.

**Comment by BoykoAlex** [comment]
@TwistyPop can you please give this [snapshot vsix](https://s3.us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.45.0-202302012342.vsix) a try?

**Comment by BoykoAlex** [comment]
I think should be fixed by now. Please re-open if you think otherwise

**Comment by martinlippert** [comment]
This should be fixed. The extensions that we publish moved to a new publisher (from the old and outdated pivotal one to VMware), but along that way we forgot to update hard-coded references to the old ID in the dashboard extension. This should all be updated now.

**Comment by TwistyPop** [comment]
Should just be able to install the extension directly through VS code by installing say the "Spring boot extension pack" or "Spring boot tools" or do I need to get the new VSIX somewhere else? 

I just tried installing the extensions directly and I'm still getting the same incompatible message.

Extension ID: vmware.vscode-spring-boot
Version: v1.44.0
Last Updated 1/31/2023, 16:51:42

**Comment by TwistyPop** [comment]
I downloaded the VSIX for v1.45.0-202302061558 at https://dist.springsource.com/snapshot/STS4/nightly-distributions.html

This version installed fine. It's just whatever is on market place needs to be updated at some point.

**Comment by martinlippert** [comment]
My comment above (https://github.com/spring-projects/sts4/issues/967#issuecomment-1419424985) is totally misleading, sorry for the noise. Sounds like this was a totally different problem. In case @BoykoAlex fixed something (as mentioned in https://github.com/spring-projects/sts4/issues/967#issuecomment-1419420557), we need to wait for the next release to appear on the marketplace and things should be fine again.

@BoykoAlex Can you point us here at the commit/change that fixes this issue?

**Comment by BoykoAlex** [comment]
This is the commit: 9a8ab05804dc291a8d91006f5817be3fcb856bdd

**Comment by davidpneda** [comment]
Hello, I work for a company that maintains a legacy Java 8 application. We were using version 1.19 of vscode-spring-boot, but it looks like it auto-updated to version 1.44. Because of that, another engineer and I are no longer able to debug our application.

**Comment by BoykoAlex** [comment]
Version 1.45 would have vscode at 1.67 and higher. If you like you can install pre-release:
![Screenshot 2023-02-24 at 21 22 09](https://user-images.githubusercontent.com/6433390/221331281-3eaa4638-65e3-4106-9a88-fe75a79443b5.png)

**Comment by davidpneda** [comment]
Another engineer and I tried using the pre-release, and our issue still persists. It looks like the newer versions no longer support Java8. Is there any way we can use the 1.19 version?

**Comment by BoykoAlex** [comment]
@davidpneda you can't install Java 17 or Java 11 to run the extension? Note, even if you run the extension with Java 17 or 11 you are still able to work with projects base on Java 8 in your workspace...
The oldest version i was able to find is 1.26: https://s3.us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.26.0-RC.2.vsix

**Comment by davidpneda** [comment]
@BoykoAlex I've updated to using Java11, have updated these extensions to the following version:
`
Spring Boot Dashboard v0.10.1
Spring Boot Tools v1.44.0
Debugger for Java v0.48.0
`
However, the spring boot dashboard is empty. Would you happen to know what could be causing that?

**Comment by BoykoAlex** [comment]
@davidpneda my bad... it should be Java 17 or higher. It should have showed an error message pop up that Spring Extensions require Java 17 or higher. I noticed that the error message didn't show up for me in the release build. Instead there is an error logged in the console (Help -> Dev Tools). Sorry for misinforming about Java 11 :-\

**Comment by davidpneda** [comment]
@BoykoAlex sounds good, thanks for the help!
